-- 将番剧计数字段改为 BIGINT，避免热门番剧 play_count 等超出 INT 范围 (1264)
-- 执行：python run_migrate.py 会按顺序执行此迁移（在 user cookie 迁移之后）

USE bilibili_bangumi;

ALTER TABLE bangumi_info
  MODIFY COLUMN play_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '播放量',
  MODIFY COLUMN follow_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '追番数',
  MODIFY COLUMN score_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评分人数',
  MODIFY COLUMN danmaku_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '弹幕总数',
  MODIFY COLUMN coin_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '投币数',
  MODIFY COLUMN fav_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '收藏数';

ALTER TABLE bangumi_daily_snapshot
  MODIFY COLUMN play_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN follow_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN danmaku_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN coin_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN fav_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN score_count BIGINT UNSIGNED NOT NULL DEFAULT 0;
